name: divergent
description: Flutter project.

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # ✅ Supports Dart 3.6.1 & Null Safety

dependencies:
  flutter:
    sdk: flutter

  # ✅ Latest null-safe dependencies
  english_words: ^4.0.0
  flutter_tts: ^4.2.2
  hexcolor: ^3.0.1
  flutter_native_splash: ^2.3.10 # ✅ Replaces `splashscreen`
  image_picker: ^1.0.7
  http: ^1.2.0
  path: ^1.8.3
  shared_preferences: ^2.2.2  
  telephony: ^0.2.0
  shake: ^2.1.0
  fluttertoast: ^8.2.2
  geolocator: ^13.0.2
  vibration: ^3.1.3
  percent_indicator: ^4.2.3
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.0.0

  # ✅ Alternative for `simple_ocr_plugin` (uses Google OCR)
  google_ml_kit: ^0.19.0 

  # ✅ Replacing old `tflite`
  tflite_flutter: ^0.11.0  
  tflite: ^1.1.2
  splash_screen_view: ^2.0.1
  colornames: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  camera: ^0.11.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/cash_model_unquant.tflite
    - assets/cash_labels.txt
    - assets/icon.jpg
    - assets/icon-circle.png
    - assets/tflite/labels.txt
    - assets/tflite/model_unquant.tflite
    - assets/images/splashScreen.png
    - assets/images/appIcon.png
    - assets/images/deaf_image.png
    - assets/images/colour_blind_image.png
    - assets/images/blind_image.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
